TARGET = main
OBJS = loadmodule.o niveau3.o kstuff.o


INCDIR =
CFLAGS = -O2 -G0 -Wall
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)



LIBDIR =
LDFLAGS =  

STDLIBS=  
LIBS =  -lpspvshbridge_2 -lpsppower_2


PSP_FW_VERSION=371
EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = Pandoriseur 3.72 HX-1


PSPSDK=C:/Cygwin/usr/local/pspdev/psp/sdk/
include $(PSPSDK)/lib/build.mak